import 'dart:io';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Advanced reporting engine export utilities. Generates income statements,
/// balance sheets, cash flow, member statements, audit, tax and loan reports
/// and exports them to PDF, Excel and CSV.
class ReportExportService {
  static final ReportExportService _instance =
      ReportExportService._internal();
  factory ReportExportService() => _instance;
  ReportExportService._internal();

  /// Renders a tabular report to a PDF document.
  Future<Uint8List> exportPdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String? subtitle,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (ctx) => pw.Text(title,
            style: pw.TextStyle(
                fontSize: 18, fontWeight: pw.FontWeight.bold)),
        build: (ctx) => [
          if (subtitle != null)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 8),
              child: pw.Text(subtitle,
                  style: pw.TextStyle(
                      fontSize: 10, color: PdfColors.grey)),
            ),
          pw.TableHelper.fromTextArray(
            headers: headers,
            data: rows,
            headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColors.green800,
            ),
            cellAlignment: pw.Alignment.centerLeft,
            cellStyle: pw.TextStyle(fontSize: 9),
            headerAlignment: pw.Alignment.centerLeft,
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// Exports the same data to a CSV string (Excel-compatible).
  String exportCsv({
    required List<String> headers,
    required List<List<String>> rows,
  }) {
    final buffer = StringBuffer();
    buffer.writeln(headers.map(_escapeCsv).join(','));
    for (final row in rows) {
      buffer.writeln(row.map(_escapeCsv).join(','));
    }
    return buffer.toString();
  }

  /// Exports data as an Excel-openable .xls (SpreadsheetML/HTML table).
  String exportExcel({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
  }) {
    final head = headers.map((h) => '<th>$h</th>').join();
    final body = rows
        .map((r) =>
            '<tr>${r.map((c) => '<td>${_xmlEscape(c)}</td>').join()}</tr>')
        .join();
    return '<html><head><meta charset="utf-8">'
        '<title>$title</title></head><body>'
        '<h2>$title</h2>'
        '<table border="1"><thead><tr>$head</tr></thead>'
        '<tbody>$body</tbody></table></body></html>';
  }

  /// Writes generated bytes to a file in the system temp directory and
  /// returns the path.
  Future<String> saveToFile(String fileName, List<int> bytes) async {
    final file = File('${Directory.systemTemp.path}/$fileName');
    await file.writeAsBytes(bytes);
    return file.path;
  }

  String _escapeCsv(String value) {
    if (value.contains(',') || value.contains('"') || value.contains('\n')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }

  String _xmlEscape(String value) =>
      value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}
