// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGw8EW5bQdt95rSDwtEbYMKrcFuWxGfRw',
    appId: '1:645114153552:web:5695e9d77cb1000f76df55',
    messagingSenderId: '645114153552',
    projectId: 'smart-chama-5ecaf',
    authDomain: 'smart-chama-5ecaf.firebaseapp.com',
    storageBucket: 'smart-chama-5ecaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72CTBsJQ5ax4TmlnEH60lMP3cQoe57j0',
    appId: '1:645114153552:android:62ee9085584246ab76df55',
    messagingSenderId: '645114153552',
    projectId: 'smart-chama-5ecaf',
    storageBucket: 'smart-chama-5ecaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBERzXecnUXhjvuLqRdZ1JG-7yUnWFB0',
    appId: '1:645114153552:ios:1bac9de7cad6666776df55',
    messagingSenderId: '645114153552',
    projectId: 'smart-chama-5ecaf',
    storageBucket: 'smart-chama-5ecaf.firebasestorage.app',
    iosBundleId: 'com.example.smartchama',
  );
}
